"""empty message

Revision ID: b10f31d90591
Revises: 
Create Date: 2026-02-25 19:58:34.380435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b10f31d90591'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('is_dev', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('youtube_videos',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('channel_title', sa.String(), nullable=True),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_table('card_definitions',
    sa.Column('card_def_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_video_id', sa.String(), nullable=True),
    sa.Column('card_name', sa.String(), nullable=False),
    sa.Column('rarity', sa.String(), nullable=True),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('attributes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_video_id'], ['youtube_videos.video_id'], ),
    sa.PrimaryKeyConstraint('card_def_id')
    )
    op.create_table('card_instances',
    sa.Column('instance_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_def_id', sa.Integer(), nullable=True),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_def_id'], ['card_definitions.card_def_id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('instance_id')
    )
    op.create_table('packs',
    sa.Column('pack_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creator_id', sa.String(), nullable=True),
    sa.Column('main_hero_instance_id', sa.Integer(), nullable=True),
    sa.Column('pack_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['main_hero_instance_id'], ['card_instances.instance_id'], ),
    sa.PrimaryKeyConstraint('pack_id')
    )
    op.create_table('marketplace_items',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('listed_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('stock', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pack_id'], ['packs.pack_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('pack_contents',
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['card_instances.instance_id'], ),
    sa.ForeignKeyConstraint(['pack_id'], ['packs.pack_id'], ),
    sa.PrimaryKeyConstraint('pack_id', 'instance_id')
    )
    op.create_table('transactions',
    sa.Column('tx_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('buyer_id', sa.String(), nullable=True),
    sa.Column('seller_id', sa.String(), nullable=True),
    sa.Column('tx_date', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['marketplace_items.item_id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('tx_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('pack_contents')
    op.drop_table('marketplace_items')
    op.drop_table('packs')
    op.drop_table('card_instances')
    op.drop_table('card_definitions')
    op.drop_table('youtube_videos')
    op.drop_table('users')
    # ### end Alembic commands ###
