"""empty message

Revision ID: e35a1e5bc034
Revises: b10f31d90591
Create Date: 2026-02-25 21:18:38.204332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e35a1e5bc034'
down_revision: Union[str, Sequence[str], None] = 'b10f31d90591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battle_log',
    sa.Column('battle_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player1_id', sa.Integer(), nullable=False),
    sa.Column('player2_id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('battle_data', sa.Text(), nullable=True),
    sa.Column('battle_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('battle_id')
    )
    op.create_table('card_cosmetics',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('cosmetic_id', sa.String(), nullable=False),
    sa.Column('equipped_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'card_id', 'cosmetic_id')
    )
    op.create_table('cosmetics_catalog',
    sa.Column('cosmetic_id', sa.String(), nullable=False),
    sa.Column('cosmetic_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rarity', sa.String(), nullable=True),
    sa.Column('unlock_method', sa.String(), nullable=True),
    sa.Column('price_gold', sa.Integer(), nullable=True),
    sa.Column('price_tickets', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cosmetic_id')
    )
    op.create_table('creator_packs',
    sa.Column('pack_id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('pack_name', sa.String(), nullable=False),
    sa.Column('card_ids', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pack_id')
    )
    op.create_table('daily_claims',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_claim_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('marketplace_listings',
    sa.Column('listing_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('listed_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_table('pack_definitions',
    sa.Column('pack_id', sa.String(), nullable=False),
    sa.Column('pack_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_gold', sa.Integer(), nullable=True),
    sa.Column('price_tickets', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('card_count', sa.Integer(), nullable=True),
    sa.Column('rarity_distribution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pack_id')
    )
    op.create_table('season_progress',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.String(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('current_tier', sa.Integer(), nullable=True),
    sa.Column('has_premium', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'season_id')
    )
    op.create_table('server_activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_history',
    sa.Column('trade_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id_1', sa.Integer(), nullable=False),
    sa.Column('user_id_2', sa.Integer(), nullable=False),
    sa.Column('card_id_1', sa.String(), nullable=False),
    sa.Column('card_id_2', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('trade_id')
    )
    op.create_table('transaction_audit_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('user_balances',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=True),
    sa.Column('dust', sa.Integer(), nullable=True),
    sa.Column('tickets', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_cosmetics',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('cosmetic_id', sa.String(), nullable=False),
    sa.Column('cosmetic_type', sa.String(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'cosmetic_id')
    )
    op.create_table('vip_status',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_vip', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_id', sa.String(), nullable=True),
    sa.Column('activity_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('users', sa.Column('discord_tag', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_active', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('total_battles', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('wins', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('losses', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('packs_opened', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('victory_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'victory_tokens')
    op.drop_column('users', 'packs_opened')
    op.drop_column('users', 'losses')
    op.drop_column('users', 'wins')
    op.drop_column('users', 'total_battles')
    op.drop_column('users', 'last_active')
    op.drop_column('users', 'discord_tag')
    op.drop_table('vip_status')
    op.drop_table('user_cosmetics')
    op.drop_table('user_balances')
    op.drop_table('transaction_audit_log')
    op.drop_table('trade_history')
    op.drop_table('server_activity')
    op.drop_table('season_progress')
    op.drop_table('pack_definitions')
    op.drop_table('marketplace_listings')
    op.drop_table('daily_claims')
    op.drop_table('creator_packs')
    op.drop_table('cosmetics_catalog')
    op.drop_table('card_cosmetics')
    op.drop_table('battle_log')
    # ### end Alembic commands ###
